# 40k steps, 3h to almost optimal, but still inconsistent
name: "Hopper"

# Environment configuration
env:
  num: 4
  name: "Hopper-v5"
  actions:
    - type: "Discretized_Continuous"
      bins: 7
      num: 3
