# MuJoCo Reacher
# Likely requires some reward formulation - specifically incremental `reward_distance`
name: "Reacher"

# Environment configuration
env:
  num: 4
  name: "Reacher-v5"
  actions:
    - type: "Discretized_Continuous"
      bins: 9
    - type: "Discretized_Continuous"
      bins: 9
    # - type: "Continuous"
    #   num_actions: 4
    #   clip: 1.0

# Replay adjustments
replay:
  ratio: 1.0

# Training adjustments
training:
  # Discount parameters
  gamma: 0.99

  # Sample dimensions
  # sequence_length: 16

# Structure adjustments
model:
  global:
    # Hidden dimensions
    blocks: 2
